### PR TITLE
Ben Stoltz 2022 predictions

### PR DESCRIPTION
**Pull request by lzrd**

### CODE REVIEW

**Comment by orangecms** [comment]
I'll add mine when this gets merged

1yr: a major OS from China emerges
3yr: high performance computing from Europe
6yr: ARM no longer as relevant

**Comment by orangecms** [comment]
Whoops, looks like @ahl just set up the file, then we need to rework this @lzrd 🙃

**Comment by lzrd** [comment]
yup. I'll be abandoning my branch and just add my row to the table.

**Comment by ahl** [comment]
@lzrd sorry about that!

**Comment by ahl** [comment]
I merged this by hand

**Pull request closed without merging**
